version: '3.9'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db
      
  node-app:
    build: .
    environment:
      - MONGODB_URI=mongodb://mongo:27017/soccer-match
      - "TZ=Asia/Kolkata"
    image: soccer_match
    ports:
      - 3000:3000
    volumes:
      - .:/app
    depends_on:
      - mongo


volumes:
  mongodata: